import React from "react";

interface DiagramComponent {
  name: string;
  path: string;
  description: string;
  dependencies: string[];
  category: string;
}

interface Props {
  component: DiagramComponent;
  repoFullName: string;
  onClose: () => void;
}

export function ComponentDetailPanel({ component, repoFullName, onClose }: Props) {
  const [activeTab, setActiveTab] = React.useState<"overview" | "tradeoffs" | "alternatives" | "why">("overview");

  const tabs = [
    { id: "overview" as const, label: "Overview" },
    { id: "tradeoffs" as const, label: "Trade-offs" },
    { id: "alternatives" as const, label: "Alternatives" },
    { id: "why" as const, label: "Why this was chosen" },
  ];

  return (
    <div
      style={{
        width: 360,
        background: "#1a1a2e",
        borderLeft: "1px solid #333",
        display: "flex",
        flexDirection: "column",
        overflow: "hidden",
      }}
    >
      <div style={{ padding: "16px 20px", borderBottom: "1px solid #333", display: "flex", justifyContent: "space-between", alignItems: "flex-start" }}>
        <div>
          <h2 style={{ margin: 0, fontSize: 16, color: "#fff" }}>{component.name}</h2>
          <p style={{ margin: "4px 0 0", fontSize: 11, color: "#888" }}>{repoFullName}</p>
          <span
            style={{
              display: "inline-block",
              marginTop: 6,
              padding: "2px 8px",
              background: "#2a2a4e",
              borderRadius: 4,
              fontSize: 11,
              color: "#aaa",
            }}
          >
            {component.category}
          </span>
        </div>
        <button
          onClick={onClose}
          style={{
            background: "none",
            border: "none",
            color: "#888",
            cursor: "pointer",
            fontSize: 18,
            padding: "4px 8px",
          }}
        >
          ×
        </button>
      </div>

      <div style={{ display: "flex", borderBottom: "1px solid #333" }}>
        {tabs.map((tab) => (
          <button
            key={tab.id}
            onClick={() => setActiveTab(tab.id)}
            style={{
              flex: 1,
              padding: "8px 4px",
              background: activeTab === tab.id ? "#2a2a4e" : "transparent",
              border: "none",
              borderBottom: activeTab === tab.id ? "2px solid #6a6aff" : "2px solid transparent",
              color: activeTab === tab.id ? "#fff" : "#888",
              cursor: "pointer",
              fontSize: 11,
            }}
          >
            {tab.label}
          </button>
        ))}
      </div>

      <div style={{ flex: 1, padding: 16, overflowY: "auto", fontSize: 13, lineHeight: 1.6 }}>
        {activeTab === "overview" && (
          <div>
            <p style={{ color: "#ccc" }}>{component.description || `${component.name} is a ${component.category}-layer component used in this architecture.`}</p>
            {component.dependencies.length > 0 && (
              <div style={{ marginTop: 16 }}>
                <strong style={{ color: "#aaa", fontSize: 12 }}>Dependencies:</strong>
                <ul style={{ margin: "8px 0", paddingLeft: 20, color: "#999" }}>
                  {component.dependencies.map((dep) => (
                    <li key={dep}>{dep}</li>
                  ))}
                </ul>
              </div>
            )}
            <p style={{ marginTop: 16, color: "#666", fontSize: 12 }}>
              Path: <code style={{ color: "#888" }}>{component.path}</code>
            </p>
          </div>
        )}

        {activeTab === "tradeoffs" && (
          <div>
            <p style={{ color: "#999", fontStyle: "italic" }}>
              Trade-off analysis will be generated by AI when you click "Analyze Component" in the full version. This shows the structure of the detail system.
            </p>
            <div style={{ marginTop: 16 }}>
              <strong style={{ color: "#e88" }}>Potential concerns:</strong>
              <ul style={{ margin: "8px 0", paddingLeft: 20, color: "#ccc" }}>
                <li>Operational complexity</li>
                <li>Scaling characteristics</li>
                <li>Maintenance overhead</li>
                <li>Learning curve</li>
              </ul>
            </div>
          </div>
        )}

        {activeTab === "alternatives" && (
          <div>
            <p style={{ color: "#999", fontStyle: "italic" }}>
              AI-generated alternatives will appear here, comparing this component against other popular choices for the same use case.
            </p>
            <div style={{ marginTop: 16, color: "#ccc" }}>
              <p>Common alternatives in this category:</p>
              <ul style={{ paddingLeft: 20 }}>
                <li style={{ marginTop: 8 }}>Self-hosted solution</li>
                <li style={{ marginTop: 8 }}>Managed cloud service</li>
                <li style={{ marginTop: 8 }}>Open-source alternative</li>
              </ul>
            </div>
          </div>
        )}

        {activeTab === "why" && (
          <div>
            <p style={{ color: "#999", fontStyle: "italic" }}>
              AI-generated analysis showing why this open-source project chose this specific component over alternatives.
            </p>
            <div style={{ marginTop: 16, padding: 12, background: "#1e1e3a", borderRadius: 8, color: "#ccc" }}>
              <p style={{ margin: 0 }}>
                The original project chose {component.name} because it fits their {component.category} requirements,
                aligns with their technology stack, and has proven production performance at their scale.
              </p>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
